import { FormEvent, useEffect, useState } from "react";
import { createDefect, createExecution, createTestCase, getDefects, getExecutions, getSummary, getTestCases, type Defect, type Execution, type Summary, type TestCase } from "./api";

const emptySummary: Summary = { total_test_cases: 0, total_executions: 0, pass_rate: 0, open_defects: 0, by_status: {} };
type FormName = "testCase" | "execution" | "defect" | null;

export default function App() {
  const [summary, setSummary] = useState<Summary>(emptySummary);
  const [cases, setCases] = useState<TestCase[]>([]);
  const [executions, setExecutions] = useState<Execution[]>([]);
  const [defects, setDefects] = useState<Defect[]>([]);
  const [form, setForm] = useState<FormName>(null);
  const [error, setError] = useState("");
  const load = () => Promise.all([getSummary(), getTestCases(), getExecutions(), getDefects()]).then(([s, c, e, d]) => { setSummary(s); setCases(c); setExecutions(e); setDefects(d); setError(""); }).catch(() => setError("API is unavailable. Start the FastAPI server on port 8000."));
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { if (form === "testCase") await createTestCase(values); if (form === "execution") await createExecution({ ...values, test_case_id: Number(values.test_case_id) }); if (form === "defect") await createDefect({ ...values, test_case_id: values.test_case_id ? Number(values.test_case_id) : null }); setForm(null); await load(); } catch { setError("Could not save the record. Check the required fields and try again."); } }
  const cards = [["Test Cases", summary.total_test_cases], ["Executions", summary.total_executions], ["Pass Rate", `${summary.pass_rate}%`], ["Open Defects", summary.open_defects]];
  return <main><header><div><p className="eyebrow">QUALITY ENGINEERING</p><h1>Test Execution Dashboard</h1><p>Track coverage, results, and defects for every release.</p></div><div className="actions"><button onClick={() => setForm("execution")}>Record result</button><button className="secondary" onClick={() => setForm("testCase")}>+ Test case</button></div></header>{error && <p className="error">{error}</p>}<section className="cards">{cards.map(([label, value]) => <article className="card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="panel"><div className="panel-title"><div><h2>Regression status</h2><p>Latest execution results</p></div><div className="legend"><span className="passed">Passed: {summary.by_status.passed ?? 0}</span><span className="failed">Failed: {summary.by_status.failed ?? 0}</span><span className="blocked">Blocked: {summary.by_status.blocked ?? 0}</span></div></div><div className="bar"><i className="pass" style={{ width: `${summary.pass_rate}%` }} /></div></section><section className="split"><section className="panel"><h2>Recent executions</h2><ul className="activity">{executions.slice(0, 5).map(item => <li key={item.id}><span className={`dot ${item.status}`} /><div><b>{cases.find(c => c.id === item.test_case_id)?.title ?? `Test case #${item.test_case_id}`}</b><small>{item.cycle} · {item.executed_by}</small></div><span className={`badge ${item.status}`}>{item.status.replace("_", " ")}</span></li>)}</ul></section><section className="panel"><div className="panel-title"><h2>Open defects</h2><button className="text-button" onClick={() => setForm("defect")}>+ Report</button></div><ul className="activity">{defects.filter(d => d.status === "open" || d.status === "in_progress").map(defect => <li key={defect.id}><span className="dot failed" /><div><b>{defect.title}</b><small>{defect.severity} severity · {defect.status.replace("_", " ")}</small></div></li>)}</ul></section></section><section className="panel"><h2>Test cases</h2><p>Manage regression coverage by module.</p><table><thead><tr><th>ID</th><th>Title</th><th>Module</th><th>Priority</th></tr></thead><tbody>{cases.map(item => <tr key={item.id}><td>TC-{item.id}</td><td>{item.title}</td><td>{item.module}</td><td><span className={`badge ${item.priority}`}>{item.priority}</span></td></tr>)}</tbody></table></section>{form && <div className="modal-backdrop" onMouseDown={() => setForm(null)}><section className="modal" onMouseDown={event => event.stopPropagation()}><div className="panel-title"><h2>{form === "testCase" ? "New test case" : form === "execution" ? "Record execution" : "Report defect"}</h2><button className="close" onClick={() => setForm(null)}>×</button></div><RecordForm kind={form} cases={cases} onSubmit={submit} /></section></div>}</main>;
}

function RecordForm({ kind, cases, onSubmit }: { kind: Exclude<FormName, null>; cases: TestCase[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="record-form" onSubmit={onSubmit}>{kind === "testCase" && <><label>Title<input name="title" required minLength={3} /></label><label>Module<input name="module" required placeholder="Authentication" /></label><label>Priority<select name="priority"><option>high</option><option defaultValue="medium">medium</option><option>low</option></select></label><label>Steps<textarea name="steps" /></label><label>Expected result<textarea name="expected_result" /></label></>}{kind === "execution" && <><CaseSelect cases={cases} required /><label>Test cycle<input name="cycle" required defaultValue="Regression v1.0" /></label><label>Result<select name="status"><option>passed</option><option>failed</option><option>blocked</option><option>not_run</option></select></label><label>Executed by<input name="executed_by" required placeholder="Your name" /></label><label>Notes<textarea name="notes" /></label></>}{kind === "defect" && <><label>Title<input name="title" required /></label><label>Severity<select name="severity"><option>critical</option><option>major</option><option>minor</option></select></label><CaseSelect cases={cases} /><label>Description<textarea name="description" /></label></>}<button type="submit">Save {kind === "testCase" ? "test case" : kind}</button></form>; }
function CaseSelect({ cases, required = false }: { cases: TestCase[]; required?: boolean }) { return <label>Related test case<select name="test_case_id" required={required}><option value="">{required ? "Select a test case" : "None"}</option>{cases.map(item => <option key={item.id} value={item.id}>TC-{item.id} · {item.title}</option>)}</select></label>; }
